mode: apps_script
apps_script_url: "https://script.google.com/macros/s/AKfycbyHaKClWmFD_cjwNAhVHccgDf35Kv5Nss9PDAY9IGr1Ae7NcfDxs4ZRWdKYzden3azP/exec"
relay_url: ""   # خالی بگذارید – پروکسی خودش apps_script_url را می‌خواند
bind_host: 127.0.0.1
bind_port: 8094
socks_enabled: true
socks_port: 1091
doh_enabled: true
doh_providers:
  - https://cloudflare-dns.com/dns-query
  - https://dns.google/resolve
mitm_enabled: true
ca_dir: ./ca
# ⚠️ برای حفظ حریم خصوصی در شرایط فیلترینگ، همه لاگ‌ها غیرفعال شدند
log_full_urls: false
log_cookies: false
log_authorization: false
log_request_bodies: false
cache_enabled: false
